name: Classes
author: c10coding
version: 1.0
main: me.caleb.Classes.Main
api-version: 1.13
depend: [Clans]
commands:
  class:
    aliases:
      - cl
    description: "Most basic command"
    permission: cl.use
      