--- 
MaxDifferenceAmount: .5
ClassList: 
- Archer
- Brute
- Ice_wizard
- Thief
- Peacemaker
Cooldowns:
  Ice Strike: .5
Classes: 
  Archer: 
    PTG cooldown: 1
    Attributes: 
      - "MaxHealth: 1"
      - "Quickness: 2"
      - "RangedDamage: 2"
      - "Resistance: 1"
      - "SpellPower: 1"
      - "Strength: 1"
      - "Toughness: 2"
    Items: 
      - "name: golden_sword; amount: 1; enchants: durability 3; customName: Dagger; lore: Keep your enemies at a distance..."
      - "name: bow; amount: 1; customName: Basic Bow; lore: Aim steady..."
      - "name: blaze_rod; amount: 1; customName: Prayer to the Gods; lore: You call on the gods to guide you to the nearest Treasure Shrine"
      - "name: leather_boots; amount: 1"
      - "name: leather_chestplate; amount: 1"
      - "name: leather_leggings; amount: 1"
      - "name: leather_helmet; amount: 1"
      - "name: arrow; amount: 64"
  Brute:
    Attributes:
      - "MaxHealth: 2"
      - "Quickness: 1"
      - "RangedDamage: 1"
      - "Resistance: 1"
      - "SpellPower: 1"
      - "Strength: 2"
      - "Toughness: 2"
    Items:
      - "name: golden_axe; amount: 1; enchants: durability 3; customName: The Brute Axe; lore: Only the strongest shalt hold this axe..."
      - "name: white_wool; amount: 1; customName: Quickening; lore: You move significantly faster for 3 seconds"
      - "name: blaze_powder; amount: 1; customName: Relentless Stand; lore: You are determined. You are unwilling to go down. You give you and your clan members the Resistance buff for 5 seconds"
      - "name: leather_boots; amount: 1"
      - "name: leather_chestplate; amount: 1"
      - "name: leather_leggings; amount: 1"
      - "name: leather_helmet; amount: 1"
  Ice_wizard:
    Attributes:
      - "MaxHealth: 1"
      - "Quickness: 1"
      - "RangedDamage: 1"
      - "Resistance: 1"
      - "SpellPower: 2"
      - "Strength: 1"
      - "Toughness: 1"
    Items:
      - "name: packed_ice; amount: 1; customName: Frost Strike; lore: Strike wisely..."
      - "name: tnt; amount: 1; customName: Knockback; lore: Use this spell sparingly wise one..."
      - "name: snowball; amount: 1; customName: Leg Weakening; lore: Spark agonizing pain in ones legs with this spell..."
      - "name: leather_boots; amount: 1"
      - "name: leather_chestplate; amount: 1"
      - "name: leather_leggings; amount: 1"
      - "name: leather_helmet; amount: 1"
  Thief: 
    Attributes: 
      - "MaxHealth: 1"
      - "Quickness: 2"
      - "RangedDamage: 1"
      - "Resistance: 1"
      - "SpellPower: 2"
      - "Strength: 2"
      - "Toughness: 1"
    Items:
      - "name: golden_sword; amount: 1; enchants: durability 3; customName: Dagger; lore: Keep your enemies at a distance..."
      - "name: wither_rose; amount: 1; customName: Stealth; lore: You descend into the shadows..."
      - "name: feather; amount: 1; customName: Quickening; lore: You move significantly faster for 3 seconds"
      - "name: spider_eye; amount: 1; customName: Eye Gouge; lore: Your enemy becomes blind as you tear their eyes apart"
      - "name: leather_boots; amount: 1"
      - "name: leather_chestplate; amount: 1"
      - "name: leather_leggings; amount: 1"
      - "name: leather_helmet; amount: 1"
  Peacemaker:
    Attributes:
      - "MaxHealth: 1"
      - "Quickness: 1"
      - "RangedDamage: 1"
      - "Resistance: 1"
      - "SpellPower: 3"
      - "Strength: 1"
      - "Toughness: 1"
    Items:
      - "name: golden_sword; amount: 1; enchants: durability 3; customName: Dagger; lore: Keep your enemies at a distance..."
      - "name: golden_carrot; amount: 1; customName: Touch of Light; lore: Bless your ally that is hurting the most within a 30 block range"
      - "name: snowball; amount: 1; customName: Leg Pain; lore: You cripple your foes and cause them to slow down"
      - "name: bricks; amount: 1; customName: Steady Front; lore: You summon a damageable wall right before your eyes"
      - "name: nautilus_shell; amount: 1; customName: Holy Rejuvenation; lore: Use this as protection my friend..."
      - "name: leather_boots; amount: 1"
      - "name: leather_chestplate; amount: 1"
      - "name: leather_leggings; amount: 1"
      - "name: leather_helmet; amount: 1"
   
  
